FROM centos:centos7
MAINTAINER Miram Technology <bentleyj68@gmail.com>

# install OpenJDK and Oracle JDK
RUN yum update -y && \
yum install -y wget && \ 
wget --header "Cookie: oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u121-b13/e9e7ea248e2c4826b92b3f075a80e441/jdk-8u121-linux-x64.rpm" && \ 
yum localinstall -y /jdk-8u121-linux-x64.rpm && \ 
rm -f /jdk-8u121-linux-x64.rpm && \
yum install -y java-1.8.0-openjdk && \ 
yum clean all

# Set environment variables. 
ENV HOME /root # Define working directory. WORKDIR /root

# Define working directory. 
WORKDIR /root

# Define default command. 
CMD ["bash"]
